services:
  web:
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    command: "python manage.py runserver 0.0.0.0:8000"
    
  db:
    image: postgres:15.1-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=patrick
      - POSTGRES_PASSWORD=patrick19135
      - POSTGRES_DB=pricetracker
  
volumes:
    postgres_data: