services:
  web:
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - rabbitmq_server
    command: "python manage.py runserver 0.0.0.0:8000"
  
  rabbitmq_server:
    image: rabbitmq:3-management
    restart: always
    env_file:
      - ./.env.dev
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery_worker:
    build: ./app     
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    depends_on:
      - rabbitmq_server
      - db
    command: "celery -A pricetracker worker -l INFO "

  celery_beat:
    build: ./app     
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    depends_on:
      - rabbitmq_server
      - db
    command: "celery -A pricetracker beat -l INFO "

  db:
    image: postgres:15.1-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=patrick
      - POSTGRES_PASSWORD=patrick19135
      - POSTGRES_DB=pricetracker
  
volumes:
    postgres_data:
    rabbitmq_data: